#!/usr/bin/env ruby

# Reserve all sectors on track 35 for hidden directory

require 'd64tools'

file = ARGV[0]

file or
  fail "Usage: #{$0} <d64-file>"

image = D64::Image.read(file)

17.times do |sn|
  image.bam.mark_as_used 35, sn
end
image.bam.commit

image.write file
